# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Joshua D. Wright, Ph.D.
description: "I am a data scientist and research scientist focused on producing business value. I currently manage research and analytics projects for executive leadership teams across Operations, Human Resources, and Finance in both a full-time and consulting capacity. My portfolio reflects the wide variety of projects I have worked on for diverse stakeholders. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "New York, NY"
resume_url: /docs/Joshua Wright Resume 1-29-2024.pdf
avatar_image: /img/IMG_2704_Cropped.jpg

#-------------------------------
# Contact links
linkedln: "www.linkedin.com/in/profjd" # Add your linkedln handle
github: "https://github.com/joshw4288"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

