# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Joshua D. Wright, Ph.D.
description: "I am a research scientist, data scientist, and people analytics practitioner. I currently direct all institutional survey research and analytics for a 12 campus technical college, which includes our research programs on student, employee, and employer experiences. This page reflects a variety of real-world projects I have worked on for diverse stakeholders in my full-time role and in a consulting capacity. You can visit my LinkedIn page or download my resume by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Analytics <span style="color:#f58506"> Portfolio </span>
location: "New York, NY"
resume_url: /docs/Resume.pdf
avatar_image: /img/IMG_2704_Cropped.jpg

#-------------------------------
# Contact links
linkedln: "https://linkedin.com/in/profjd" # Add your linkedln handle
github: "https://github.com/joshw4288"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

